// THIS FILE WAS GENERATED BY bridge.view AND SHOULD NOT BE MODIFIED

library templates_2015_09_05_05_19_59_795;

import "package:bridge/view.dart";


@proxy
class Templates extends TemplateCollection {
  Map<String, TemplateGenerator> get templates => {
    "app": () async => new Template(parsed: """<!DOCTYPE html>
<html lang='en'>

<head>
    <title>Bridge</title>
    <link rel='stylesheet' href='/app.css'>
    <script src='//use.typekit.net/dcz8uda.js'></script>
    <script>
        try {
            Typekit.load();
        } catch (e) {}
    </script>
</head>

<body>
    ${await $include('partials.header')}
    ${$block('content')}
</body>

</html>""", data: data),
    "error": () async => new Template(parsed: """${await $extends('app', {'content': """
  <h3>
    ${message ?? 'Oops! Something went wrong!'}
    ${await (() async => (code != 200 && code != null) ? """
      <small>($code)</small>
    """ : "")()}</h3>

  
  ${await (() async => (Environment.isDevelopment && stackTrace != null) ? """
    <h6>$exception</h6>
    <pre class='stack-trace'>${$escape($instantiate(#Chain.forTrace, stackTrace).terse.toString())}</pre>
  """ : "")()}"""})}""", data: data),
    "index": () async => new Template(parsed: """${await $extends('app', {'content': """
  <style>
    body, html, .wrap-all {
        height:100%;
        width:100%;
    }
    img {
        max-width: 20em;
        box-sizing: border-box;
        padding: 1em 0;
        width:100%;
    }
    .wrap-all {
        display: table;
    }
    .wrap-row {
        display: table-row;
    }
    .wrap-cell {
        display: table-cell;
        vertical-align: middle;
        text-align: center;
    }
    iframe {
        display: inline-block;
        margin: auto;
        width: 6.5em;
        padding-top: 0.2em;
        vertical-align: bottom;
    }
  </style>
  <div class="wrap-all">
    <div class="wrap-row">
      <div class="wrap-cell">  
      <div>
        <img src="http://dart-bridge.github.io/images/logo-blue.svg" alt="Bridge">
      </div>

      <iframe src="https://ghbtns.com/github-btn.html?user=dart-bridge&amp;repo=framework&amp;type=star&amp;count=true" frameborder="0" scrolling="0" height="20px"></iframe>
      <iframe src="https://ghbtns.com/github-btn.html?user=dart-bridge&amp;repo=framework&amp;type=watch&amp;count=true&amp;v=2" frameborder="0" scrolling="0" width="170px" height="20px"></iframe>

      <h6>
        This will be the new documentation site, itself built on Bridge.<br>
        Until it's done, please refer to
        <a href="//dart-bridge.github.io">dart-bridge.github.io</a>
      </h6>
    </div>
  </div>
</div>
"""})}""", data: data),
    "partials.header": () async => new Template(parsed: """<header id="header">
  hej
</header>""", data: data),
  };
}